### PR TITLE
Created the option for rclone copy or rclone sync in the config/env

### PR DESCRIPTION
**Pull request by eliasbenb**
To enable `rclone sync`, instead of `rclone copy`, add `RCLONE_SYNC` as `true` to the environment variables or the config.

It defaults to `rclone copy`.

### CODE REVIEW

**Comment by eliasbenb** [comment]
bump

**Comment by MsGsuite** [comment]
Hi,
Thanks for this. I will look at it asap

**Comment by MsGsuite** [comment]
Your changes are not working for me @eliasbenb

**Comment by eliasbenb** [comment]
> Your changes are not working for me @eliasbenb

Sorry, the `RCLONE_SYNC` option didn't work from the `config.ini` file previously, it just worked from the environment variable.

It should work now.

**Comment by MsGsuite** [comment]
Hi,
Each time that I try the new code I have this error
```
Traceback (most recent call last):
  File "C:\Users\administrateur\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\administrateur\Desktop\CloneBot-master\telegram_gcloner\utils\fire_save_files.py", line 54, in run
    if os.getenv('RCLONE_SYNC').lower() == 'true' or config.RCLONE_SYNC.lower() == 'true':
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by eliasbenb** [comment]
I think you forgot to pull the new commit I made.

> Hi,
> Each time that I try the new code I have this error
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\administrateur\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "C:\Users\administrateur\Desktop\CloneBot-master\telegram_gcloner\utils\fire_save_files.py", line 54, in run
>     if os.getenv('RCLONE_SYNC').lower() == 'true' or config.RCLONE_SYNC.lower() == 'true':
> AttributeError: 'NoneType' object has no attribute 'lower'
> ```

**Comment by ShiroUwUs7** [comment]
@eliasbenb Do you know if there would be a way to allow rclone --drive-impersonate email@domain.com flag to use with 'My Drive' ? (after updating it to newer gclone version from v1.57 rclone as the dependency.
